### ISSUE TITLE
Questing Black steel quest bug

### ISSUE THREAD

**Issue by floorwaxer2** [AllTheMods/Gravitas2#113]
![2024-01-15_21 22 30](https://github.com/AllTheMods/Gravitas2/assets/48165383/e43ba1ee-3f2e-4129-9c64-d1d5ad18acd9)
![2024-01-15_21 22 28](https://github.com/AllTheMods/Gravitas2/assets/48165383/35ad07cc-3d66-47bd-8417-adb6566ce207)
![2024-01-15_21 23 24](https://github.com/AllTheMods/Gravitas2/assets/48165383/19d5146d-bfc0-4876-8f76-b57b4c941dba)
![2024-01-15_21 23 21](https://github.com/AllTheMods/Gravitas2/assets/48165383/24227a10-e48f-4fc0-a12e-f7ef771f6c03)

You need TFC black steel to complete the quest but when black steel is made it turns into Gregtech black steel.

**Comment by floorwaxer2** [comment]
Adding to this is the same with red steel and blue steel quests

**Comment by Bizuex** [comment]
Indeed this is a problem.

**Comment by metus1** [comment]
I've hit this same problem and it killed my experience in the modpack.
