### ISSUE TITLE
0.1.9-a "Alternator" recipe from "Create Crafts & Additions" can't be made

### ISSUE THREAD

**Issue by bjmn55** [AllTheMods/Gravitas2#146]
The "Alternator" recipe from "Create Crafts & Additions" requires an "Iron Rod" which can only be made with an "Iron Ingot" (minecraft:iron_ingot). As far as I can tell, there is no way of making or getting the required "Iron Ingot".

**Comment by thevortex** [comment]
definitely can, its an alloy furnace recipe in gregtech, cast iron ingot + lime

**Comment by bjmn55** [comment]
> definitely can, its an alloy furnace recipe in gregtech, cast iron ingot + lime

I apologize, didn't notice that. Thanks.
