### ISSUE TITLE
Game stuck at night time

### ISSUE THREAD

**Issue by ViniciusPolachini** [AllTheMods/Gravitas2#154]
At some point the game stuck at night time. If I sleep, it will still be night. If I wait, it will still be night.

**Comment by bjmn55** [comment]
Assuming you are playing Single Player, try typing the following in game:
`/gamerule doDaylightCycle true`

**Comment by ViniciusPolachini** [comment]
@bjmn55 thanks, it worked! If i have the problem again, i will try understand what trigger this and bring here again in more details.

**Comment by Radon8472** [comment]
I think this could happen if you have game crashes, or anything that stops the game from fully running the Start/ Stop Scripts.

This seems to be related to #112 and TerraFirmaCraft/TerraFirmaCraft#2562

**Comment by pap1723** [comment]
This should be good to close?

**Comment by Pumpkin7266** [comment]
fixed on tfc side so can be closed probably
