### ISSUE TITLE
No way to get tungsten

### ISSUE THREAD

**Issue by GoldenMine0502** [AllTheMods/Gravitas2#168]
there's no material for IV tech
idk how to go to end or get rocket

**Comment by Azaysol** [comment]
Im pretty sure its just not in yet

**Comment by GoldenMine0502** [comment]
![image](https://github.com/AllTheMods/Gravitas2/assets/27873716/03c60df7-6a96-4183-95a8-774c5f5b75a8)
Titanium -> Tungsten steel
arc furnace can do nuclear fusion lol
