### ISSUE TITLE
In world render issue with ingot localization - 0.2.1a

### ISSUE THREAD

**Issue by NachtRaben** [AllTheMods/Gravitas2#169]
In game ignot stacks now have a rendering issue, localization of the ingots in world seems to be a side effect.
When ingots are in inventory they are localized and rendered properly. 

Currently know ingots are Copper, Tin, and Nickel

Nyxane says its an issue with one of the scripts

Purely opening this for tracking of future reports of the same issue.

![image](https://github.com/AllTheMods/Gravitas2/assets/4164436/f6441569-de19-451b-b435-42e51e181cb5)

**Comment by pietro-lopes** [comment]
Fixed in dev
https://github.com/AllTheMods/Gravitas2/commit/c9b41531f15d7808e78f4df122d02901156824d7
