### ISSUE TITLE
Problems with axle on pump station

### ISSUE THREAD

**Issue by GustavovtLeme** [AllTheMods/Gravitas2#170]
when i put a alxe on the pump station to start irrigating the grennhouse the game simply stop working after update 0.2.1

**Comment by pietro-lopes** [comment]
please provide crash log or latest.log
https://mclo.gs/

**Comment by GustavovtLeme** [comment]
[latest.log](https://github.com/AllTheMods/Gravitas2/files/14316966/latest.log)
[crash-2024-02-16_20.58.11-server.txt](https://github.com/AllTheMods/Gravitas2/files/14316967/crash-2024-02-16_20.58.11-server.txt)

**Comment by pietro-lopes** [comment]
It is the aqueduct, revert update to fix while we fix this

**Comment by GustavovtLeme** [comment]
OK. thanks

**Comment by thevortex** [comment]
update the gravitas re-cored mod to 1.0.25 issues with aqueduct are resolved https://legacy.curseforge.com/minecraft/mc-mods/gravitas2-re-cored/files/5113721
