### ISSUE TITLE
0.2.1-a The game crashes If there is a marble aqueduct nearby 

### ISSUE THREAD

**Issue by Adskii148** [AllTheMods/Gravitas2#174]
[crash-2024-02-18_09.30.25-server.txt](https://github.com/AllTheMods/Gravitas2/files/14321166/crash-2024-02-18_09.30.25-server.txt)
It didn't crash on the previous version

**Comment by thevortex** [comment]
try updating the gravitas re-cored mod, a full pack update is coming in the next day or so but that mod update should solve it

**Comment by Adskii148** [comment]
Updating the Gravitas² Re-Cored mod from version 1.0.24 to version 1.0.25 fixed the crash

**Comment by Adskii148** [comment]
Updating the Gravitas² Re-Cored mod from version 1.0.24 to version 1.0.25 fixed the crash
