### ISSUE TITLE
 [Bug][0.2.1-a]: Exception generating new chunk. WorldGenDragonCaveMixin

### ISSUE THREAD

**Issue by Labraid** [AllTheMods/Gravitas2#175]
While exploring server crashed. Can re-start the server but when I connect and it tries to re-gen the chunks it keeps crashing. Trying to delete latest chunks without changing seed or removing mod does not fix the issue.
 
[crash-2024-02-18_19.57.47-server.txt](https://github.com/AllTheMods/Gravitas2/files/14324155/crash-2024-02-18_19.57.47-server.txt)

Since logs strongly hint at IceAndFire I also created a bug report there

**Comment by thevortex** [comment]
this is definitely on our end, watch for a coremod (Gravitas² Re-Cored) update later today, pack update coming as well

**Comment by GustavovtLeme** [comment]
i'm with the same problem
[crash-2024-02-18_19.11.36-server.txt](https://github.com/AllTheMods/Gravitas2/files/14324618/crash-2024-02-18_19.11.36-server.txt)

**Comment by GustavovtLeme** [comment]
Problem continues after update 0.2.2
[crash-2024-02-18_22.36.26-server.txt](https://github.com/AllTheMods/Gravitas2/files/14325359/crash-2024-02-18_22.36.26-server.txt)

**Comment by Labraid** [comment]
this was confirmed to be a bug on the side of Ice and Fire, was fixed in 1.20 dev version
https://github.com/AlexModGuy/Ice_and_Fire/issues/5176

**Comment by thevortex** [comment]
can i get your worldseed please? and was this the coords x=-1293.50, y=71.00, z=10140.36 ?

**Comment by Labraid** [comment]
> can i get your worldseed please? and was this the coords x=-1293.50, y=71.00, z=10140.36 ?

seed 978420934390640167
x=940.46, y=62.10, z=9569.85

not sure if those are the coords that already triggered the world gen, if not just move south-east until you see the shore

**Comment by GustavovtLeme** [comment]
My seed and location 
![image](https://github.com/AllTheMods/Gravitas2/assets/67663440/4fad4efb-ffc0-48a4-b760-412cd7c0bdd8)
I was trying go to the river when crash happens

**Comment by thevortex** [comment]
> > can i get your worldseed please? and was this the coords x=-1293.50, y=71.00, z=10140.36 ?
> 
> seed 978420934390640167 x=940.46, y=62.10, z=9569.85
> 
> not sure if those are the coords that already triggered the world gen, if not just move south-east until you see the shore

![2024-02-18_19 30 25](https://github.com/AllTheMods/Gravitas2/assets/1524819/1853597f-bd10-41f5-a652-ec4c6f062c90)
this shore?

**Comment by thevortex** [comment]
> My seed and location ![image](https://private-user-images.githubusercontent.com/67663440/305768416-4fad4efb-ffc0-48a4-b760-412cd7c0bdd8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDgzMDg1NDQsIm5iZiI6MTcwODMwODI0NCwicGF0aCI6Ii82NzY2MzQ0MC8zMDU3Njg0MTYtNGZhZDRlZmItZmZjMC00OGE0LWI3NjAtNDEyY2Q3YzBiZGQ4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjE5VDAyMDQwNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWFjYTZjZDBkYmZmZDA3ZTVlZjYwZTYyZGY2NjAxMjcyMjMwYjFjNmUxYmNjYWNkNTFhN2Q0YjEyYzg0MWIzMGMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.2eWIozsN-Vsra7aJL7ThL5yS5FBCNbNQwRw3Xc5VkZU) I was trying go to the river when crash happens

![2024-02-18_19 33 24](https://github.com/AllTheMods/Gravitas2/assets/1524819/c8def8a6-067d-4a39-9cb1-b60d313e4ebd)
i'm in the river

**Comment by thevortex** [comment]
have either of you used create tree fertilizer in this world? dont do it if you havent just curious

**Comment by Labraid** [comment]
> > > can i get your worldseed please? and was this the coords x=-1293.50, y=71.00, z=10140.36 ?
> > 
> > 
> > seed 978420934390640167 x=940.46, y=62.10, z=9569.85
> > not sure if those are the coords that already triggered the world gen, if not just move south-east until you see the shore
> 
> ![2024-02-18_19 30 25](https://private-user-images.githubusercontent.com/1524819/305772303-1853597f-bd10-41f5-a652-ec4c6f062c90.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDgzMTY3MzQsIm5iZiI6MTcwODMxNjQzNCwicGF0aCI6Ii8xNTI0ODE5LzMwNTc3MjMwMy0xODUzNTk3Zi1iZDEwLTQxZjUtYTY1Mi1lYzRjNmYwNjJjOTAucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDIxOSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAyMTlUMDQyMDM0WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZTkwYzQ3ZjE0Njc2MDhlNGJkNzNiYTZhOTVkYzQ3YzkwMjJiOTYyYTI3NmI2ODIyNDRlMGQwMmQ2ZTYxMzNlNyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.79DGNYBNX7G66bwyzHDOaGvMIq0d1aSyCupcOke6RaY) this shore?

no, what I suspect to be a bigger continental mass is further south-east

**Comment by GustavovtLeme** [comment]
Ok I used it, is there any way I can solve this? or will I have to create a new map using the same seed and rebuild everything?

**Comment by thevortex** [comment]
> Ok I used it, is there any way I can solve this? or will I have to create a new map using the same seed and rebuild everything?

first did you use it near your base? this just came to my attention today that this tree fertilizer use will lead to new chunks not getting their data stored properly, if you didnt use it at your base you should* be ok to copy your base chunks into a new world with the same seed

**Comment by GustavovtLeme** [comment]
So i lost my base <o>

**Comment by Labraid** [comment]
> have either of you used create tree fertilizer in this world? dont do it if you havent just curious

so far I only used terrafirma ones on crops, haven't touched create yet, but its good to know that I shouldn't

**Comment by pietro-lopes** [comment]
> So i lost my base or there is another solution?

Try to reach me on Discord @Uncandango
zip your save and DM me your world

**Comment by pietro-lopes** [comment]
> i can't find you on Discord using @Uncandango

Join ATM Discord first
https://discord.gg/allthemods

**Comment by GustavovtLeme** [comment]
I've created a new world with the same seed, didn'nt used any item and just use create mod to fly and i'm getting a crash 
[crash-2024-02-19_15.24.21-server.txt](https://github.com/AllTheMods/Gravitas2/files/14335835/crash-2024-02-19_15.24.21-server.txt)
i'm thinking in leave this modpack to play in the future

**Comment by pietro-lopes** [comment]
> I've created a new world with the same seed, didn'nt used any item and just use create mod to fly and i'm getting a crash [crash-2024-02-19_15.24.21-server.txt](https://github.com/AllTheMods/Gravitas2/files/14335835/crash-2024-02-19_15.24.21-server.txt) i'm thinking in leave this modpack to play in the future

You are using outdated version of coremod, use this one <https://www.curseforge.com/minecraft/mc-mods/gravitas2-re-cored/files/5119115>

**Comment by Labraid** [comment]
Can confirm that 0.2.2-a solves reported issue completely. Thank you.
