### ISSUE TITLE
woodencog as Create compatibel to TFC >> crafting recipes also iron_plates  >> in V-0.2.2.a

### ISSUE THREAD

**Issue by zukkl** [AllTheMods/Gravitas2#183]
there is also the woodcog addon, which still has iron plates instead of wrought iron plates. Please do not forget :D 

e.g.
create:empty_blaze_burner
[https://i.imgur.com/mn5hLgm.png](https://i.imgur.com/mn5hLgm.png)

create:item_vault (double recipe from create and woodencog)
[https://i.imgur.com/cP8HJ6V.png](https://i.imgur.com/cP8HJ6V.png)
[https://i.imgur.com/s6HFcT9.png](https://i.imgur.com/s6HFcT9.png)

create_filter 
[https://i.imgur.com/MV7mBSM.png](https://i.imgur.com/MV7mBSM.png)

**Comment by Labraid** [comment]
speaking of iron plates, is it intended for GT coke oven to be locked behind iron plates? It is reachable through low pressure steam alloy furnace and forge hammer, but it feels like it should be more low tech than this.

**Comment by Radon8472** [comment]
> speaking of iron plates, is it intended for GT coke oven to be locked behind iron plates? It is reachable through low pressure steam alloy furnace and forge hammer, but it feels like it should be more low tech than this.

Good point, but maybe you should write this in an own issue, Ithink this does not realy fit to the topic of this issue
