### ISSUE TITLE
Distant Horizons support?

### ISSUE THREAD

**Issue by lith-x** [AllTheMods/Gravitas2#184]
I tried to manually throw in the most recent release of the Distant Horizons mod (v. alpha 2.0.1 for 1.20.1, [link](https://www.curseforge.com/minecraft/mc-mods/distant-horizons/files/4924664)). There's various incompatibilities that throw errors when generating/rendering the world. Don't expect anything because this does sound like a whole thing with scope and work, but thought it wouldn't hurt to ask.

if at all interested, here's an error log [link](https://paste.ee/p/ij10C)

**Comment by SnackJunkie** [comment]
I had the same issue and it looks like it's fixed by manually updating all the mods (just ctrl+a and check for updates), but only for new worlds. Not sure which mod is responsible.

**Comment by SnackJunkie** [comment]
Never mind, it still crashes

**Comment by thevortex** [comment]
maybe try with this combo of graphics related mods versions
![image](https://github.com/AllTheMods/Gravitas2/assets/1524819/74c52573-bc73-4c1d-8417-98e891c75608)

**Comment by SnackJunkie** [comment]
This is what's installed by default with the pack

**Comment by lith-x** [comment]
I did some digging.

Distant Horizons acts a tad funky and throw errors left and right with TerraFirmaCraft. Ultimately what this is screwing up is just DH's own chunk generation and sometimes chunk rendering, but the actual hard crash seems to come from TFC Thermal Deposits (seems like DH doesn't like the way it's trying to handle fluids, but I'm not too sure).

Workaround with limited (but still some!) functionality:
- Disable TFC Thermal Deposits
  - previous worlds generated with this mod may act a bit funny (i haven't experienced a crash doing this yet, but I can't say with confidence a crash won't happen, worldgen freaks out under the hood)
- Set DH>Advanced>World Generator to "Pre-existing Chunks Only"
  - until the conflict is resolved, this setting doesn't do much, pre-render just prevents the error spam from TFC

**Comment by lith-x** [comment]
With a workaround found, and an actual fix needing to come from mod devs and outside the control of the maintainers here, I'll close this off.
