### ISSUE TITLE
Anvil recipe needs more iron, than can fit in the alloy smelter input

### ISSUE THREAD

**Issue by Radon8472** [AllTheMods/Gravitas2#191]
The recipe for the anvli (I mean the classic anvil for adding enchanments) takes 31 Iron ingots and a molt.
![2024-02-26_22 32 52](https://github.com/AllTheMods/Gravitas2/assets/30496382/5e85644e-8575-4fcb-bd5e-df42683a95d1)

**The problem is,** 
that ingots in this pack will only stack up to 16 items, what means you can not put more than 16 Iron into the input slot of the allow smelter, which makes the recipe impossible.

![2024-02-26_23 25 40](https://github.com/AllTheMods/Gravitas2/assets/30496382/49928e35-67d4-44ab-836b-cd9ffc752df5)

**How to reproduce:**
- Try to put 31 Iron ingot and a molt into the alloy smelter

**Possible Solution:**
For me it makes sense, that an anvill should need 31 iron (according to the vanilla recipe) and I see 2 possible sulutions for this issue:

- either the recipe is changed to max. 16 Iron ingots
- OR you change the input to double iron plates, which are basicly the 32 iron ignots so nearly the same price like the desired input

**Affected Pack versions:**
- 0.2.2-a

**Comment by thevortex** [comment]
fluid solidifier is the correct recipe to use for the vanilla iron

**Comment by Radon8472** [comment]
> fluid solidifier is the correct recipe to use for the vanilla iron anvil

Are you realy sure that you like to make an anvil to an end game item??
This would apotheosis nearly useless, when you can not use any enchantments

**Comment by thevortex** [comment]
enchantments are OP during early game, did you see the recipe for the enchanting table? its HV
