### ISSUE TITLE
Game Crashes on World Creation - MAC OS 14.1.1 (23B81)

### ISSUE THREAD

**Issue by superdusto** [AllTheMods/Gravitas2#197]
Here is the crash log.
https://pastebin.com/F5jyEdvu

**Comment by thevortex** [comment]
pastebin link is not valid for me already, please use https://mclo.gs for sharing any logs/crash reports plz

**Comment by superdusto** [comment]
Here is the Microsoft Game Output
https://mclo.gs/tVaJcCt

**Comment by superdusto** [comment]
Here is the crash log.
https://mclo.gs/5xz2URO

**Comment by thevortex** [comment]
can you try relaunching with the spark mod removed?

**Comment by superdusto** [comment]
That did it. Thank you!
