### ISSUE TITLE
[0.2.5-a] No macerator byproducts below HV, chances do not match JEI tooltip

### ISSUE THREAD

**Issue by Labraid** [AllTheMods/Gravitas2#201]
For raw and crushed ore processing in macerator steam, LV and MV versions produce no additional outputs despite chance being shown in JEI. Additional outputs only start showing up with HV (Advanced Macerator II), this matches issues that was reported in GTCEu github (https://github.com/GregTechCEu/GregTech-Modern/issues/687). It was attributed back then to ATM9 config override.

Early game is already penalized plenty by less efficient recipes and lack of other means (with other tech mods, I am aware of washing step providing outputs since LV) of getting GT specific metals and minerals thus I don't think that this change should be propagated to this modpack. 

![Macerator_test](https://github.com/AllTheMods/Gravitas2/assets/8479358/7716b013-35c2-4ba3-b887-29c1d6778968)

**Comment by Azaysol** [comment]
JEI will always show possible results, however GT Macerator does not provide byproducts till HV, its listed in its description:

![image](https://github.com/AllTheMods/Gravitas2/assets/1907447/b34e3347-b1c2-4e97-8c73-f0f31aea2f62)

![image](https://github.com/AllTheMods/Gravitas2/assets/1907447/1914b824-c2ae-4730-b855-b032ea4e91d7)

**Comment by screret** [comment]
intended.

**Comment by screret** [comment]
wait I HAVE RIGHTS STILL???

**Comment by screret** [comment]
I won't grief because I'm not a little shit
@thevortex please, take away my rights.

**Comment by screret** [comment]
I'd ping you in the discord server but you muted me for a week because I was trying to have a civil discussion.

**Comment by screret** [comment]
ok cool IG you don't want to remove my rights then :)

**Comment by screret** [comment]
damn now it worked, thanks!

**Comment by screret** [comment]
could've not deleted my comments though...
