### ISSUE TITLE
Conflicting Pyrolyse Oven Recipes

### ISSUE THREAD

**Issue by vhxk** [AllTheMods/Gravitas2#238]
The recipe for creosote matches the recipe for wood vinegar, making the wood vinegar an impossible craft with the pyrolyse oven as it gets overridden by the creosote recipe
![image](https://github.com/AllTheMods/Gravitas2/assets/162056295/c2874e06-b9a2-4461-b117-fd237b51ab69)
![image](https://github.com/AllTheMods/Gravitas2/assets/162056295/a4245c08-112b-4085-932e-3ed5975c8855)

**Comment by strider820** [comment]
These use two different configurations on the programmed circuit - Creosote uses configuration 1 while wood vinegar uses configuration 7. These recipes aren't actually conflicting
