### ISSUE TITLE
{ATM9}[Mod Addition Request] Immersive Engineering addon, Engineered Compatibility 

### ISSUE THREAD

**Issue by trechetican** [AllTheMods/Gravitas2#256]
Good day all 
there is a mod called Engineered Compatibility  by VoidsongDragonfly, which i think would be a good fit for the pack, adding lot's of compatibility to immersive engineering. it is also endorsed by Blusunrize the creator of IE 

https://www.curseforge.com/minecraft/mc-mods/engineered-compatibility 
https://modrinth.com/mod/engineered-compatibility

**Comment by thevortex** [comment]
for Gravitas² or ATM9?

**Comment by trechetican** [comment]
Yeah sorry I edited the title after to say atm9
