### ISSUE TITLE
bloomery is not working

### ISSUE THREAD

**Issue by Crackis271** [AllTheMods/Gravitas2#257]
**Build Version:** 0.3.1-a
**Adding or Changing:** None

**Link to the video:** _https://youtu.be/YoLOK4fWans_
**Logs:** 
[latest.log](https://github.com/AllTheMods/Gravitas2/files/15071010/latest.log)

I create a bloomery according to the instructions of TFC, I throw 16 charcoal and 16 cast iron. They don't turn into blocks of ore. I tried different bricks, different ores, tried everything and nothing helped.

**Comment by AirRice** [comment]
This is a known issue in the current release, https://github.com/AllTheMods/Gravitas2/commit/94dc606e16d2e57ebe1ac7b11fe76e10ef0c9bbc addressed this. Will be fixed next release.
