### ISSUE TITLE
bloomery

### ISSUE THREAD

**Issue by AtqEpiletico** [AllTheMods/Gravitas2#262]
the bloomery is not working, its all builded correctly, but does not recognize the items inside
![Captura de tela 2024-04-24 193006](https://github.com/AllTheMods/Gravitas2/assets/168039630/4699adcd-aef8-41e5-9788-543d06fb30f8)

**Comment by AtqEpiletico** [comment]
i have also tested in other world, same...

**Comment by thevortex** [comment]
will be fixed in next update!
