### ISSUE TITLE
Cannot craft bronze (early game)

### ISSUE THREAD

**Issue by FarekEE** [AllTheMods/Gravitas2#267]
I'm in the early game, and I'm unable to craft bronze because all attempt turns the alloy into brass (8-12% zinc, 92-88% copper).
I tried both ends of the range and got two jars of unusable waste (for now I hope)

**Comment by G1R-Productions** [comment]
It is 8-12% TIN and 88-92% copper
Not zinc. Zinc and copper makes brass.
