### ISSUE TITLE
0.3.2-a Immersive engineering multiblocks being disabled isn't communicated to the player

### ISSUE THREAD

**Issue by ArcaneDefence** [AllTheMods/Gravitas2#276]
Standard construction leads to rotating the conveyor belt when right clicked with the engineer's hammer, instead of forming the multiblock structure as expected
My power loom constructs just fine, so this threw me off

![image](https://github.com/AllTheMods/Gravitas2/assets/51932756/2f9130bf-8b62-4a92-b145-344b7c66fb4d)
![image](https://github.com/AllTheMods/Gravitas2/assets/51932756/f96c5722-c27d-4426-b7f7-dada097dac64)
![image](https://github.com/AllTheMods/Gravitas2/assets/51932756/936655b5-afaf-44c7-a0b9-24caeb2ee1c1)

**Comment by Nyxane** [comment]
All of the IE multis are disabled

**Comment by ArcaneDefence** [comment]
Is that communicated anywhere?

**Comment by Nyxane** [comment]
Ill write up a PR to communicate that via IE Hammer, so... it will be in the next ipdate
