### ISSUE TITLE
0.3.2-a Soda ash is too easy to make when trying to make tfc dried kelp

### ISSUE THREAD

**Issue by ArcaneDefence** [AllTheMods/Gravitas2#278]
Trying to make tfc dried kelp without a filtered output in the following ways makes soda ash too fast for the player to react to, which can make people think it's uncraftable

![image](https://github.com/AllTheMods/Gravitas2/assets/51932756/dc341f80-8abc-4953-a84b-56a9860a57f9)

![image](https://github.com/AllTheMods/Gravitas2/assets/51932756/eaf605fe-7b02-4572-a203-42656352a9a1)

**Comment by Gaelmare** [comment]
Put a filtered chute/funnel on the depot and it can pull the dried kelp out before the next recipe procs

**Comment by Gaelmare** [comment]
If you cook it on a firepit, it will drop into the output slot.

**Comment by ArcaneDefence** [comment]
Thanks for further clarification
