### ISSUE TITLE
How to get naquadah

### ISSUE THREAD

**Issue by Nanyunyune** [AllTheMods/Gravitas2#286]
I can't go to the end,so how can i gain naquadah to go to ZPM?

**Comment by Radon8472** [comment]
I tried to use stargates to reach abydos (where you could find naquada), unfortunally in my world it seems that no stargate structure is spawned :(

You could try if cou can find a burried stargate in your world

**Comment by Nanyunyune** [comment]
> I tried to use stargates to reach abydos (where you could find naquada), unfortunally in my world it seems that no stargate structure is spawned :(
> 
> You could try if cou can find a burried stargate in your world

I can't find stargates too. I suspect it's disabled.

**Comment by Radon8472** [comment]
> > I tried to use stargates to reach abydos (where you could find naquada), unfortunally in my world it seems that no stargate structure is spawned :(
> > You could try if cou can find a burried stargate in your world
> 
> I can't find stargates too. I suspect it's disabled.

Am am afraid you are right.
But accourding jei you cna get naquada in the end or on abydos....
so if both ways are blocked, we are back to the question in the issue headline 😞
