### ISSUE TITLE
0.3.3-a Macerator does not yield secondary items?

### ISSUE THREAD

**Issue by Hybr1sX** [AllTheMods/Gravitas2#287]
While using the macerators on low tier (low pressure, high pressure, basic and advanced) I noticed that the recipes for ores, that have a chance to yield bonus items, doesn't yield any. I tried it in creative afterwards and it works with macerators that are HV and higher.

Is that supposed to be or is there a problem with the recipes on low tier?

**Comment by RadzRatz** [comment]
byproducts only come in HV and higher tiers
