### ISSUE TITLE
there is a few items under normal minecraft iron rather then wought iron.

### ISSUE THREAD

**Issue by npincus** [AllTheMods/Gravitas2#291]
either their recipe should be disable or they should move to wrought iron.
once found so far are rolling mill plates, glider frame and crafting upgrade

**Comment by npincus** [comment]
simmulearly iron backpack is under terriaferma and minecraft iron not gregtech iron

**Comment by syrun97** [comment]
i think it is intended cuz there is recipe for vanilla iron
![2024-06-01_23 11 33](https://github.com/AllTheMods/Gravitas2/assets/19798397/6406413e-95ec-4d97-b00f-c4996ecd9b5e)

**Comment by MAIMBRAIN** [comment]
This can be a bit confusing if a player is following the quest book. It shows the Create Rolling Mill is dependent on Wrought Iron Plate but the actual recipe for the Create Rolling Mill requires vanilla iron to make it instead.

So it begins > Blast Furnace (To make a different Anvil)
![image](https://github.com/AllTheMods/Gravitas2/assets/15690549/ac7dfcbd-990e-4080-9cf8-261085c30e18)

**Comment by npincus** [comment]
yeah that was the problem the quest were misleading
