### ISSUE TITLE
Crash on start up

### ISSUE THREAD

**Issue by Naliga** [AllTheMods/Gravitas2#313]
As title says. on updates 0.3.7-a to 0.3.9-b

Last line:
free(): double free detected in tcache 2

Version 0.3.6-a works fine

Crash happens just as the main menu loads

**Comment by thevortex** [comment]
can you try in a fresh instance, backup your world, configs/xaeros map, and failing that, can you share the full logs

**Comment by Naliga** [comment]
Fresh install on 0.3.9-b

Latest:
[latest.log](https://github.com/user-attachments/files/16087132/latest.log)

Debug:
[debug.log](https://github.com/user-attachments/files/16087138/debug.log)

Console:
[console.log](https://github.com/user-attachments/files/16087156/console.log)

**Comment by Naliga** [comment]
Still valid on 0.4.0
Same last line

**Comment by thevortex** [comment]
how much ram are you allocating?

**Comment by thevortex** [comment]
min 6 to 8 gb, recommend 12

**Comment by Naliga** [comment]
Same with 6, 8, 12 and 12+ gb allocated

**Comment by Proxwian** [comment]
Fresh install, 0.4.0, not workie

**Comment by Wyrmlet** [comment]
Same thing here, version 0.4.0 fresh install crashes as soon as main menu loads, log ends with "double free or corruption (fasttop)"

**Comment by GodOfLac** [comment]
I got same, it seem only effect with linux user, and solution is update Distant Horizon to 2.1.2-a

**Comment by Naliga** [comment]
> I got same, it seem only effect with linux user, and solution is update Distant Horizons to 2.1.2-a

Can confirm updating DH to 2.1.2-a fixes the issue.
