### ISSUE TITLE
Crash linux game start

### ISSUE THREAD

**Issue by Zekirax** [AllTheMods/Gravitas2#319]
When I start the game it reaches the introduction with the narrator. I hear the "Na" from narrator then it's freeze and 2 seconds later it crashes with exit code 6. On linux exit code 6 means SIGABRT. On windows it works perfectly. 

Distributor ID:	Linuxmint
Description:	Linux Mint 21.3
Release:	21.3
Codename:	virginia
kernel : 6.5.0-41-generic

**Comment by pietro-lopes** [comment]
Which Graphic card and Drivers?

**Comment by Zekirax** [comment]
gpu : RTX 2060 
NVIDIA Driver Version : 550.90.07
no crash logs
[latest.log](https://github.com/user-attachments/files/16128106/latest.log)

**Comment by pietro-lopes** [comment]
Can you add to your `/etc/environment` this line?
`__GL_THREADED_OPTIMIZATIONS=0`
and restart PC

**Comment by Zekirax** [comment]
I added a rule on the nvidia settings. Process name with java have GLThreadedOptimizations=false. It worked thanks. Can you explain why it works please ?

**Comment by pietro-lopes** [comment]
I don't know, it is just NVIDIA and their Drivers, some versions it works fine, some doesn't...

**Comment by Zekirax** [comment]
Is it a long time problem ?
