### ISSUE TITLE
[0.4.0] copper ores don't spawn at alll

### ISSUE THREAD

**Issue by J4ckTh3R1pper** [AllTheMods/Gravitas2#322]
in 0.3.9b there was still native copper from tfc, however at 0.4.0 all tfc metal ores seemed to be removed? how should I go on?

**Comment by thevortex** [comment]
![2024-07-13_15 47 40](https://github.com/user-attachments/assets/dd45450f-ab22-4e1c-9ae1-d78b42a2cda4)
can confirm on a new world that native copper(and other copper) do still generate on 0.4.0 it can be hard to find but it is spawning
