### ISSUE TITLE
Cannot craft Treated wood rod

### ISSUE THREAD

**Issue by J4ckTh3R1pper** [AllTheMods/Gravitas2#326]
![2024-07-22_00 09 07](https://github.com/user-attachments/assets/94614880-066b-418d-9872-bed8d67e19c5)
version is 0.4.0, on dedicated server

**Comment by adventurerok** [comment]
Same applies for treated wood fluid pipes, I tried to make them but I just got regular wooden ones instead

**Comment by ArcaneDefence** [comment]
As a player a workaround I found success in having JEI autofill the recipe into a backpack crafting module

**Comment by Pumpkin7266** [comment]
fixed in latest
![image](https://github.com/user-attachments/assets/45c98e4a-bcb1-41fd-8ebc-19d60449f5d2)
