### ISSUE TITLE
game crashing on start

### ISSUE THREAD

**Issue by mogibesf** [AllTheMods/Gravitas2#337]
exit code 1
[latest.log](https://github.com/user-attachments/files/16845986/latest.log)
[debug.log](https://github.com/user-attachments/files/16845987/debug.log)
logs doesnt say anything

**Comment by soufhehe** [comment]
try renaming the folder to remove the ² from the folder name

**Comment by mogibesf** [comment]
worked, ty!

> try renaming the folder to remove the ² from the folder name
