### ISSUE TITLE
Quests inconsistencies 

### ISSUE THREAD

**Issue by squillis** [AllTheMods/Gravitas2#346]
The Black, Red and Blue Anvils quest tab, for the red and blue buckets probably need a revamp, or just removed. Red and Blue buckets no longer place sources of lava/water and are not used to create a vanilla bucket anymore.
![image](https://github.com/user-attachments/assets/ad4a5a7b-0dba-4f1b-aec5-0634c7fbe348)

- - - - -New Find- - - - -
GregTech/ High Voltage, Enchanting Table.
It says mythic gems, that's the old naming style, they're now called Flawless Gems for the required craft.
![image](https://github.com/user-attachments/assets/c617a75d-de8f-4573-a376-e0e72b3b53d3)

**Comment by squillis** [comment]
Chapter 1:Getting Started, Eating 101
Giving TFC food for quest rewards i'm told is hard/doesn't work? It always gives rotten food. Might consider a random food seed or just not giving food as rewards maybe. 
![image](https://github.com/user-attachments/assets/56d4ca5a-1acb-45c0-84a7-99184acbeefb)
![image](https://github.com/user-attachments/assets/959c988d-a263-4ed8-bc8d-845fbe73ffd5)

**Comment by squillis** [comment]
Chapter 1:Getting Started, The First Metal Tools
For this quest the other metal tools are oredic with other bronze tool parts, but the axe just has copper.
![image](https://github.com/user-attachments/assets/27a92acf-c280-4c72-855a-63747a7796ca)
![image](https://github.com/user-attachments/assets/94244561-e5c0-46fa-b0a0-0113bd5e567c)
![image](https://github.com/user-attachments/assets/19e1df24-2979-4a19-96d5-622b84c0d64b)

**Comment by squillis** [comment]
When collecting quest rewards with EXP it shows a white icon, might consider using EXP orb icon or bottle o' enchanting icon.
![image](https://github.com/user-attachments/assets/47cabc51-44f0-4d47-a7c4-8ea5065bf2ea)

**Comment by squillis** [comment]
Chapter 1 :Getting Started, Oak Tool Rack
Might consider changing name and oredic the different wood tool racks? It requires only oak instead of other wood types.
![image](https://github.com/user-attachments/assets/9851db5a-cfbf-4db3-aa97-94dc72b567f4)
![image](https://github.com/user-attachments/assets/783e1665-eb56-41c1-9cd5-3332ce38410c)

**Comment by squillis** [comment]
Stage 2: Using Anvils, Raw Graphite.
This quest only accepts Gregtech Raw Graphite, should probably be TFC Graphite also.
![image](https://github.com/user-attachments/assets/2626ce36-c513-4bce-bef8-306b55f264a8)
![image](https://github.com/user-attachments/assets/73fb161b-8ebd-4124-9dc9-1c00165de684)

**Comment by TheBedrockMaster** [comment]
Thank you for these, if you add anything else please have it be apart of the first comment though.

**Comment by squillis** [comment]
Alright, I'll add future finds to first post, sorry.

**Comment by squillis** [comment]
![image](https://github.com/user-attachments/assets/9bc16f46-7777-4eb8-98af-c9a8c1482d58)

I thought you said to add to first post, but that's gone now? So.......here? lol

**Comment by TheBedrockMaster** [comment]
For any more please make a new issue
