### ISSUE TITLE
[Question] Disabling finite water

### ISSUE THREAD

**Issue by hron84** [AllTheMods/Gravitas2#347]
Hi!

I ask here because the Discord link on the Curseforge page is broken, I cannot join to your Discord with that link.

Is it possible to disable finite water in the modpack? I having troubles with it, probalby intentional things (water jugs consume water, even in rivers, barrels perform poorly in collecting rainwater, etc), also I would like to opt-out this enhancement from my world.

Thanks for your great development on this modpack anyway.

**Comment by thevortex** [comment]
the configs for this are in the TFC Volcanoes mod, you can re-enable water infinity there, thanks for letting me know about the discord link, this should be current for the discord https://discord.gg/XS5GwPfv
i'll update the mod page accordingly as well :)

**Comment by hron84** [comment]
Thank you very much for your great assistance!
