### ISSUE TITLE
Unable to obtain gaseous radon,ender air and plutonium

### ISSUE THREAD

**Issue by SPDXSN** [AllTheMods/Gravitas2#354]
quantum eye and quantum star need it
EV emitter need quantum eye
EV laser engraver need EV emitter
希望能尽快补全相关配方
I hope to complete the relevant formula as soon as possible
气态氡和钚的获取
Acquisition of gaseous radon and plutonium

**Comment by Pumpkin7266** [comment]
fixed in latest. plutonium dust is obtained via fire dragons
