### ISSUE TITLE
Soda Ash recipe missing?

### ISSUE THREAD

**Issue by onjahhh** [AllTheMods/Gravitas2#366]
![image](https://github.com/user-attachments/assets/daf5db57-5b4f-4886-b31e-523ac0f2678d)

Soda Ash from Terrafirmacraft does not have a recipe and it is usually able to be obtained from dried seaweed. I was trying to make reinforced glass for the greenhouse and the glassworking tab shows it can be made via a process of flattening, soda ash and pouring, I tried using saltpeter as substitute but it did not work. I made sure it was not just the recipe by spawning in soda ash and using it, after which, it worked. I don't know if this is intentional or not but it does not seem intentional?

**Comment by Pumpkin7266** [comment]
![image](https://github.com/user-attachments/assets/c22d1383-c9cc-492b-95fe-f09c4aa9ac80)
fixed in latest i think
