### ISSUE TITLE
TFC Anvil doesnt work at all

### ISSUE THREAD

**Issue by phoenixburn119** [AllTheMods/Gravitas2#396]
Gravitas 2 - 0.4.5
Once upgraded to the newest version on our server a few players noticed when you tried to use the anvil the steps/status doesnt display on the menu(screenshot included). Looks as if you've not picked a recipe but if you click the smithing buttons it flashes for a moment and goes away, every time you click the button. Unsure what the cause it but I dont see other reports, I'd appreciate help if it's on my server only because I am able to replicate it along with other players.
![Screenshot 2024-11-23 124051](https://github.com/user-attachments/assets/d71bc2a1-ebea-4fb7-a564-d15fffe2aa28)

**Comment by Pumpkin7266** [comment]
yeah, TFC issue unfortunately.

**Comment by phoenixburn119** [comment]
> yeah, TFC issue unfortunately.

Ah I see, hopefully a fix comes soon. Thanks!

**Comment by robbert229** [comment]
The release of v0.4.6 resolves this issue.

**Comment by robbert229** [comment]
@thevortex this can be closed
