### ISSUE TITLE
small copper ore pieces quest broken

### ISSUE THREAD

**Issue by hacker-on-steroids** [AllTheMods/Gravitas2#414]
![image](https://github.com/user-attachments/assets/03ee36f2-4636-48a1-a2a5-1d7889735a0f)

i tried both native copper and malachite pebbles and neither seems to work

![image](https://github.com/user-attachments/assets/83222728-bb10-4b4a-932f-1cc6ba455a0b)

**Comment by TheBedrockMaster** [comment]
Mine works correctly, try on a new blank install.
