### ISSUE TITLE
Cannot create Zinc dust

### ISSUE THREAD

**Issue by MeeyoMy** [AllTheMods/Gravitas2#424]
Hello, im playing Gravitas2 and i cannot create Zinc dust. I have version 0.4.8. Im using Flint Mortar and Zinc Ingot, which i've seen videos of it working, but it doesnt work for me. Any ideas? Thanks in advance

![image](https://github.com/user-attachments/assets/c705723f-c48b-4f54-a9c4-7a7c8f9482ba)
![image](https://github.com/user-attachments/assets/e469462d-e5c4-4db6-b8cd-879a6ef231f1)
![image](https://github.com/user-attachments/assets/ae6f61a5-f038-456f-9031-9960e43076fc)

**Comment by Pumpkin7266** [comment]
fixed in dev

**Comment by BennyTheSen** [comment]
Came here for the same, thank you!
