### ISSUE TITLE
[FEATURE/QOL] Move Menu UI elements

### ISSUE THREAD

**Issue by jbagwell27** [AllTheMods/Gravitas2#64]
Currently the Forge Modloader info is blocking a huge chunk of the menu elements in default gui scale

![image](https://github.com/AllTheMods/Gravitas2/assets/53024286/e56405be-fe0e-4dbb-8267-b6d963c9e3f8)

**Comment by screret** [comment]
Pls dont use auto gui scale it breaks a lot of stuff

**Comment by jbagwell27** [comment]
That was the default for the pack. I usually have my gui set to 3. Even
with the 2x gui scale, with the default window size, it still cuts off the
GUI.
I'm suggesting to either change the menu UI, or adjust the defaults.

**Comment by jbagwell27** [comment]
To be fair. this is ONLY for the title screen. moving the elements options closer to the center would fix the entire thing
