### ISSUE TITLE
Gregtech bronze tools with wrong icon in Anvil

### ISSUE THREAD

**Issue by henriquesw** [AllTheMods/Gravitas2#75]
A few itens of gregtech are with wrong icons in the TerrafirmaCraft Anvil
I tried to craft Bronze Wrench Base and it didn't finished the crafting after getting the right sequence.

List of itens:

- Bronze File
- Bronze Wrench Base
- Bronze Wrench Claw

![image](https://github.com/AllTheMods/Gravitas2/assets/28535929/ceb18417-8249-4cd6-aa3f-5b0eedc90334)

**Comment by Angel-Abaddon** [comment]
its not wrong icons its wrong order( backwards)

**Comment by MoralPyromaniac** [comment]
you need to hover over the sequence. it isnt always in the correct order but sometimes says something along the lines of this one last.
