### ISSUE TITLE
I cant craft Dry kelp blocks needed for the hose for create.

### ISSUE THREAD

**Issue by MoralPyromaniac** [AllTheMods/Gravitas2#84]
I cant craft Dry kelp blocks needed for the hose for create.
![2024-01-01_21 42 07](https://github.com/AllTheMods/Gravitas2/assets/155337213/6c2cd16d-4a6a-4b1e-a530-1316996f1583)

**Comment by MoralPyromaniac** [comment]
Edit: still an issue but you can get around it using create compacting

**Comment by Pumpkin7266** [comment]
fixed in latest recipe uses leather
