### ISSUE TITLE
Broken questline?

### ISSUE THREAD

**Issue by Savage-Soviet** [AllTheMods/Gravitas2#91]
![problem 1](https://github.com/AllTheMods/Gravitas2/assets/34694426/50c46761-1bda-4f45-a2dc-abcf73e13905)
![problem 2](https://github.com/AllTheMods/Gravitas2/assets/34694426/4fc1f2f3-ea20-49b5-ab9f-02599982b223)
This questline requires an item that doesnt exist in version 0.1.3 does a newer version fix this?

**Comment by ramseyspace** [comment]
same issue here too
