### ISSUE TITLE
No way to get red alloy?

### ISSUE THREAD

**Issue by GoldenMine0502** [AllTheMods/Gravitas2#95]
I can't find any ULV recipe to craft red alloy

Red alloy currently needs LV Input at least

no silicon, no alloy smelter, no mixer, no terrafirma, ...

**Comment by GoldenMine0502** [comment]
has create mixer

**Comment by GoldenMine0502** [comment]
has create mixer

**Comment by screret** [comment]
Steam machines can do LV recipes.

**Comment by GoldenMine0502** [comment]
idk why the recipe doesnt work before on steam smelter
